name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
# {Repo Name} - { Pipeline Description }


trigger: none


variables:
  backendContainerName: firewallpolicycollection # blob in storag account
  terraformFilesPath: 'ESLZ/terraform/network/firewallpolicycollection'

variables:
  - template: templates/template-common-variables.yml

pool:
  name: $(agentPoolName)


steps:

  - bash: env
    displayName: "List env vars"

    # TF init
  - template: templates/template-tf-init.yml
    # parameters:
    #   backend_rgstorageaccount_name: $(backendResourceGroup)
    #   backend_ststatefiles_name: $(backendStorageAccount)
    #   backend_container_name: $(backendContainerName)
    #   tf_code_path: $(terraformFilesPath)
    #   backend_serviceconnection: $(backendServiceArm)
  
  # - template: templates/template-tf-plan.yml
  #   parameters:
  #     env_service_connection: $(backendServiceArm)
  #     tf_code_path: $(tf_code_path)