name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  name: TF-ESLZ-DEV

variables:
  rg_storageaccount_name: nov-rg-sbx-tfstatefile-001
  st_stfiles_name: novstsbxtfstate01
  
  container_name: firewallpolicycollection
  tf_code_path: 'ESLZ/terraform/network/firewallpolicycollection'
  backendServiceArm: 'tf-eslz-deployment'


steps:

  - template: templates/template-tf-init.yml
    parameters:
      backend_rgstorageaccount_name: $(rg_storageaccount_name)
      backend_ststatefiles_name: $(st_stfiles_name)
      backend_container_name: $(container_name)
      tf_code_path: $(tf_code_path)
      backend_serviceconnection: $(backendServiceArm)
  
  - template: templates/template-tf-plan.yml
    parameters:
      env_service_connection: $(backendServiceArm)
      tf_code_path: $(tf_code_path)