name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
# {Repo Name} - { Pipeline Description }

parameters:
- name: location
  displayName: Location
  type: string
  default: australiaeast
  values:
    - australiaeast
    - australiacentral
    - australiasoutheast


trigger: none

variables:
  ## common environment variables
  - template: templates/template-common-variables.yml

  ## backend specific for this pipeline variables
  - name: backendContainerName # blob in a storage account
    value: firewall # + location
  
  ## path to the tf root dir
  - name:  terraformFilesPath
    value: 'ESLZ/terraform/network/firewall'
  
  ## service connection to target if it's different from backend
  - name: environmentServiceConnection 
    value: $(backendServiceConnection)


  ##TERRAFORM ENV VARS
  - name: TF_VAR_environment
    value: $(environment)
  - name: TF_VAR_location
    value: ${{parameters.location}}

pool:
  name: $(agentPoolName)


stages:
  - template: templates/template-tf-generic.yml

