name: Deploy Public DNS
on:
  push:
    branches:
      - main
    paths:
      - 'main.bicep'
      - 'Apps/public-dns/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_PUBLIC_DNS_CRED }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      with:
        # scope: 'subscription'
        region: 'Australia East'
        resourceGroupName: 'rg-public-dns-01'
        # subscriptionId: ${{ env.MSDN_SUB }}
        # resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Apps/public-dns/bicep/main.bicep
        parameters: ./Apps/public-dns/bicep/parameters.json
        failOnStdErr: false